export default [
	{
		title: 'Mountain',
		projectLink: 'https://poly.google.com/u/1/view/6qp53W5djC5',
		text: 'This object is a part of the project <a href="https://github.com/servinlp/forgo">Forgo</a> (coming soon). Here it was used to create a part of the scenerie responsible for helping you relax.<br><br><br><br><br><br><br><br><br>',
		for: 'School',
		thumbnail: '/image/mountain.png',
		filePath: '/objects/mountain/',
		path: '/project/mountain',
		object: 'model.obj',
		material: 'material.mtl',
		scale: 6,
		boxSize: { x: 6, y: 6, z: 12 },
		position: { x: 6, y: 7, z: 0 },
		positionTo: { x: 4, y: 4, z: 2 },
		tools: [ [ 'Google Blocks', 'https://vr.google.com/blocks/' ] ]
	},
	{
		title: 'Console',
		projectLink: 'https://github.com/servinlp/Console',
		text: '<p>Not necessarily VR but a little project that saved me a lot of time and problems. With this you can write your console to the DOM. The reason I started this project was because I wanted to have a console inside of VR. This was my first step in this project. To make one inside the DOM. Problem with making this for VR was performance. Whenever something was put in the console a new TextGeometry would be added. The more you added the more it would start to crash.</p><p>Current uses for this project is when i’m working for the GearVR. Because this does not have a console this makes it so much easier.</p><br><br><br><br><br>',
		for: 'Free time',
		thumbnail: '/image/console-512.png',
		texture: '/image/console-512.png',
		textureBoxSize: { x: 5, y: 5, z: 1 },
		boxSize: { x: 6, y: 6, z: 6 },
		position: { x: -10, y: -1, z: 0 },
		positionTo: { x: 4, y: 4, z: 8 },
		rotateTo: { x: 0, y: -( ( Math.PI / 180 ) * 40 ), z: 0 }
	},
	{
		title: 'Fire Wood',
		projectLink: 'https://poly.google.com/u/1/view/2aMwBNdr0vb',
		text: 'This object is a part of the project <a href="https://github.com/servinlp/forgo">Forgo</a> (coming soon). Here it was used to create a part of the scenerie responsible for helping you relax.',
		for: 'School',
		thumbnail: '/image/fire-wood.png',
		filePath: '/objects/fire-wood/',
		path: '/project/fire-wood',
		object: 'model.obj',
		material: 'material.mtl',
		scale: 6,
		boxSize: { x: 6, y: 6, z: 8 },
		position: { x: 0, y: -1, z: 0 },
		positionTo: { x: 4, y: 4, z: 4 },
		tools: [ [ 'Google Blocks', 'https://vr.google.com/blocks/' ] ]
	},
	{
		title: 'Hand',
		projectLink: 'https://poly.google.com/u/1/view/cVUVOtHGRn_',
		text: 'This object is a part of the project <a href="https://github.com/servinlp/forgo">Forgo</a> (coming soon). Here it was used to create a part of the scenerie responsible for helping you relax.<br><br><br><br><br><br><br>',
		for: 'School',
		thumbnail: '/image/hand.png',
		filePath: '/objects/hand/',
		path: '/project/hand',
		object: 'model.obj',
		material: 'material.mtl',
		scale: 6,
		boxSize: { x: 6, y: 6, z: 6 },
		position: { x: 10, y: -1, z: 0 },
		positionTo: { x: 4, y: 4, z: 4 },
		tools: [ [ 'Google Blocks', 'https://vr.google.com/blocks/' ] ]
	},
	{
		title: 'Interactive Wireflow',
		projectLink: 'https://github.com/servinlp/interactive-wireflow',
		text: `<p>Tijdens het school project 99 verhalen hebben wij meerdere keren een digitale wireflow moeten maken in een programma als illustrator. Bij mij kwam toen de gedachte, waarom zijn we hier een statische wireflow van een website aan het maken als dit ook interactief kan. Uit deze gedachte is dit projectje een beetje ontstaan (wat ik toen alsnog in mijn vrije tijd heb gemaakt).</p>`,
		for: 'Free time',
		thumbnail: '/image/interactive-wireflow-512.png',
		texture: '/image/interactive-wireflow-512.png',
		textureBoxSize: { x: 5, y: 5, z: 1 },
		boxSize: { x: 6, y: 6, z: 6 },
		position: { x: -10, y: -10, z: 0 },
		positionTo: { x: 4, y: 4, z: 8 },
		rotateTo: { x: 0, y: -( ( Math.PI / 180 ) * 40 ), z: 0 }
	},
	{
		title: 'Forgo - HTC Vive',
		projectLink: 'https://github.com/servinlp/forgo',
		text: `<p>“Open source (web)VR solution to take a break from it all” Our end project for the project Designing for emerging technologies. Mo (a classmate of mine) and I wanted to create a world where people could enter to shut themselves off from the outside world and take a moment to relax.</p><a class="button" href="https://github.com/moniac">Mo's github</a>`,
		for: 'School',
		thumbnail: '/image/forgo-512.png',
		texture: '/image/forgo-512.png',
		textureBoxSize: { x: 5, y: 5, z: 1 },
		boxSize: { x: 6, y: 6, z: 6 },
		position: { x: 0, y: -10, z: 0 },
		// position: { x: 0, y: -1, z: 0 },
		positionTo: { x: 4, y: 4, z: 8 },
		rotateTo: { x: 0, y: -( ( Math.PI / 180 ) * 40 ), z: 0 }
	},
	{
		title: 'Amsterdone',
		projectLink: 'http://amsterdone.nl/',
		text: `<p>As winner of the project ISGA (International Students Guide Amsterdam), <a href="https://meesrutten.me/">Mees Rutten</a> had the opportunity to make his idea into a functioning product. His idea was to create a checklist with which the international students could discover Amsterdam</p><p>To help him with the project he asked <a href="http://sophieanne.nl/">Sophie Peijnenburg</a> and me. Sophie for the content, Mees for the Front end and me for the Back end. During the project we stood in direct contact with the client, Rose Leighton and later during the project with the MIC minor students.</p><br><br><br><br><br><br><br>`,
		for: 'School',
		thumbnail: '/image/amsterdone-512.png',
		texture: '/image/amsterdone-512.png',
		textureBoxSize: { x: 5, y: 5, z: 1 },
		boxSize: { x: 6, y: 6, z: 6 },
		position: { x: 10, y: -10, z: 0 },
		positionTo: { x: 4, y: 4, z: 8 },
		rotateTo: { x: 0, y: -( ( Math.PI / 180 ) * 40 ), z: 0 }
	}
]